"""add cached_searches table

Revision ID: 637cccdebcc9
Revises: 03e70fb2fa47
Create Date: 2026-08-16 16:28:35.378996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '637cccdebcc9'
down_revision: Union[str, None] = '03e70fb2fa47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table('cached_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('normalized_query', sa.String(length=500), nullable=False),
    sa.Column('raw_query', sa.String(length=500), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cached_searches_subject'), 'cached_searches', ['subject'], unique=False)
    op.create_index(op.f('ix_cached_searches_normalized_query'), 'cached_searches', ['normalized_query'], unique=False)
    op.create_index(
        'ix_cached_searches_normalized_query_trgm', 'cached_searches', ['normalized_query'],
        unique=False, postgresql_using='gin', postgresql_ops={'normalized_query': 'gin_trgm_ops'},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cached_searches_normalized_query_trgm', table_name='cached_searches', postgresql_using='gin')
    op.drop_index(op.f('ix_cached_searches_normalized_query'), table_name='cached_searches')
    op.drop_index(op.f('ix_cached_searches_subject'), table_name='cached_searches')
    op.drop_table('cached_searches')
    # Intentionally not dropping the pg_trgm extension - it may be relied on elsewhere.
    # ### end Alembic commands ###
