"""add courses materials recordings

Revision ID: 8dd1cdb251ad
Revises: 637cccdebcc9
Create Date: 2026-08-16 16:52:33.361632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dd1cdb251ad'
down_revision: Union[str, None] = '637cccdebcc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('semester', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_slug'), 'courses', ['slug'], unique=True)
    op.create_index(op.f('ix_courses_semester'), 'courses', ['semester'], unique=False)
    # Hand-added: pg_trgm GIN index on course name, so GET /api/courses?search= can do
    # fast fuzzy ILIKE/similarity matching over Cyrillic course names (pg_trgm was
    # already enabled by migration 637cccdebcc9, so no CREATE EXTENSION needed here).
    op.create_index(
        'ix_courses_name_trgm', 'courses', ['name'],
        unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'},
    )
    op.create_table('course_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'url', name='uq_course_materials_course_url')
    )
    op.create_index(op.f('ix_course_materials_course_id'), 'course_materials', ['course_id'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=False),
    sa.Column('presenter', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('video_url', sa.String(length=1000), nullable=False),
    sa.Column('source_page_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'video_url', 'topic', name='uq_recordings_course_url_topic')
    )
    op.create_index(op.f('ix_recordings_course_id'), 'recordings', ['course_id'], unique=False)
    # ### end Alembic commands ###
    # Note: autogenerate also tried to drop 'ix_cached_searches_normalized_query_trgm'
    # here, because that GIN index was hand-added in 637cccdebcc9 and isn't expressible
    # on the model - that's a false diff, intentionally dropped from this migration.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recordings_course_id'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_course_materials_course_id'), table_name='course_materials')
    op.drop_table('course_materials')
    op.drop_index('ix_courses_name_trgm', table_name='courses', postgresql_using='gin')
    op.drop_index(op.f('ix_courses_semester'), table_name='courses')
    op.drop_index(op.f('ix_courses_slug'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
